# Default configuration for video generation
video_generation:
  model: "veo-2.0-generate-001" # alternative: "veo-3.0-generate-preview"
  number_of_videos: 1
  duration_seconds: 8
  aspect_ratio: "16:9"
  enhance_prompt: true
  # all settings below not supported in gemini-api, only vertex, 
  # leave below fields commented out for compatibility
  # seed: 42
  # negative_prompt: ""
  # person_generation: "allow" # "allow" or "disallow"
  # fps: 24
  # generate_audio: false
  # not supported in vertex-api either
  # resolution: "720p" # e.g., "1080p", "720p"  # 1080p not supported veo-2
  # compression_quality: "OPTIMIZED" # "LOSELESS"

# Default configuration for image generation
image_generation:
  model: "imagen-4.0-generate-preview-06-06" # alternative: "imagen-4.0-ultra-generate-preview-06-06"
  number_of_images: 1
  aspect_ratio: "16:9" # "1:1", "3:4", "4:3", "9:16", "16:9"
  guidance_scale: 7.5
  person_generation: "ALLOW_ADULT" # "DONT_ALLOW", "ALLOW_ADULT", "ALLOW_ALL"
  output_mime_type: "image/png" # "image/png" or "image/jpeg"
  # all settings below not supported in gemini-api, only vertex, 
  # leave below fields commented out for compatibility
  # language: "en" # "auto", "en", "ja", "ko", "hi", "zh", "pt", "es"
  # enhance_prompt: true
  # seed: 42
  # negative_prompt: ""

# Default workspace settings:
workspace_setting:
  gcs_output_bucket: "gs://hello-world-123"
  local_output_dir: "data/"
