# Default configuration for video generation
video_generation:
  number_of_videos: 1
  fps: 24
  duration_seconds: 5
  aspect_ratio: "16:9"
  resolution: "1080p" # e.g., "1080p", "720p"
  person_generation: "allow" # "allow" or "disallow"
  enhance_prompt: true
  generate_audio: false
  compression_quality: "high" # "high", "medium", "low"
