# Default configuration for video generation
video_generation:
  number_of_videos: 1
  duration_seconds: 8
  aspect_ratio: "16:9"
  enhance_prompt: true
  # not supported in gemini-api, only vertex
  # person_generation: "allow" # "allow" or "disallow"
  # fps: 24
  # generate_audio: false
  # not supported in vertex-api either
  # resolution: "720p" # e.g., "1080p", "720p"  # 1080p not supported veo-2
  # compression_quality: "OPTIMIZED" # "LOSELESS"
