[project]
name = "vidstr"
version = "0.1.1"
description = "Query Veo via Gemini + Vertex for Loop-Videos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow",
    "google-genai",
    "python-dotenv",
    "opencv-python",
]
